CREATE TABLE IF NOT EXISTS public.advertisements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_type text,
  type text,
  content text,
  imgs text,
  admin_id bigint,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='ad_type') THEN
    ALTER TABLE public.advertisements ADD COLUMN ad_type text;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='type') THEN
    ALTER TABLE public.advertisements ADD COLUMN type text;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='content') THEN
    ALTER TABLE public.advertisements ADD COLUMN content text;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='imgs') THEN
    ALTER TABLE public.advertisements ADD COLUMN imgs text;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='admin_id') THEN
    ALTER TABLE public.advertisements ADD COLUMN admin_id bigint;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='created_at') THEN
    ALTER TABLE public.advertisements ADD COLUMN created_at timestamp with time zone DEFAULT timezone('utc'::text, now());
  END IF;
END $$;

ALTER TABLE public.advertisements ALTER COLUMN ad_type DROP NOT NULL;

ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous insert" ON public.advertisements;
DROP POLICY IF EXISTS "Allow anonymous select" ON public.advertisements;
DROP POLICY IF EXISTS "anon_insert" ON public.advertisements;
DROP POLICY IF EXISTS "anon_select" ON public.advertisements;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.advertisements;
DROP POLICY IF EXISTS "Enable insert for anon users" ON public.advertisements;
DROP POLICY IF EXISTS "Allow public insert" ON public.advertisements;
DROP POLICY IF EXISTS "Allow public select" ON public.advertisements;

CREATE POLICY "Allow public insert on advertisements"
  ON public.advertisements
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Allow public select on advertisements"
  ON public.advertisements
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Allow public delete on advertisements"
  ON public.advertisements
  FOR DELETE
  TO anon, authenticated
  USING (true);

GRANT ALL ON public.advertisements TO anon;
GRANT ALL ON public.advertisements TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE public.advertisements_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.advertisements_id_seq TO authenticated;

GRANT INSERT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO anon;
GRANT INSERT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO authenticated;
GRANT SELECT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO anon;
GRANT SELECT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO authenticated;

NOTIFY pgrst, 'reload schema';

