-- =====================================================
-- 广告表权限修复 SQL
-- 请在 Supabase SQL Editor 中执行以下命令
-- =====================================================

-- 1. 检查并确保 advertisements 表存在且结构正确
CREATE TABLE IF NOT EXISTS public.advertisements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_type text NOT NULL,
  type text,  -- 兼容字段
  content text,
  imgs text,  -- JSON字符串
  admin_id bigint,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. 如果表已存在但缺少列，添加缺失的列
DO $$ 
BEGIN
  -- 添加 ad_type 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='ad_type') THEN
    ALTER TABLE public.advertisements ADD COLUMN ad_type text;
  END IF;
  
  -- 添加 type 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='type') THEN
    ALTER TABLE public.advertisements ADD COLUMN type text;
  END IF;
  
  -- 添加 content 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='content') THEN
    ALTER TABLE public.advertisements ADD COLUMN content text;
  END IF;
  
  -- 添加 imgs 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='imgs') THEN
    ALTER TABLE public.advertisements ADD COLUMN imgs text;
  END IF;
  
  -- 添加 admin_id 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='admin_id') THEN
    ALTER TABLE public.advertisements ADD COLUMN admin_id bigint;
  END IF;
  
  -- 添加 created_at 列（如果不存在）
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='advertisements' AND column_name='created_at') THEN
    ALTER TABLE public.advertisements ADD COLUMN created_at timestamp with time zone DEFAULT timezone('utc'::text, now());
  END IF;
END $$;

-- 3. 修改 ad_type 为可空（如果之前设置为NOT NULL导致问题）
ALTER TABLE public.advertisements ALTER COLUMN ad_type DROP NOT NULL;

-- 4. 启用 Row Level Security（RLS）
ALTER TABLE public.advertisements ENABLE ROW LEVEL SECURITY;

-- 5. 删除所有现有的 advertisements 表的策略（避免冲突）
DROP POLICY IF EXISTS "Allow anonymous insert" ON public.advertisements;
DROP POLICY IF EXISTS "Allow anonymous select" ON public.advertisements;
DROP POLICY IF EXISTS "anon_insert" ON public.advertisements;
DROP POLICY IF EXISTS "anon_select" ON public.advertisements;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.advertisements;
DROP POLICY IF EXISTS "Enable insert for anon users" ON public.advertisements;
DROP POLICY IF EXISTS "Allow public insert" ON public.advertisements;
DROP POLICY IF EXISTS "Allow public select" ON public.advertisements;

-- 6. 创建新的 RLS 策略，允许 anon 和 authenticated 角色进行 INSERT
CREATE POLICY "Allow public insert on advertisements"
  ON public.advertisements
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- 7. 创建新的 RLS 策略，允许 anon 和 authenticated 角色进行 SELECT
CREATE POLICY "Allow public select on advertisements"
  ON public.advertisements
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 8. 创建新的 RLS 策略，允许 anon 和 authenticated 角色进行 DELETE
CREATE POLICY "Allow public delete on advertisements"
  ON public.advertisements
  FOR DELETE
  TO anon, authenticated
  USING (true);

-- 9. 授予 anon 角色对整个表的所有权限
GRANT ALL ON public.advertisements TO anon;
GRANT ALL ON public.advertisements TO authenticated;

-- 10. 授予 anon 角色对序列的使用权限（如果存在自增ID）
GRANT USAGE, SELECT ON SEQUENCE public.advertisements_id_seq TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.advertisements_id_seq TO authenticated;

-- 11. 明确授予对所有列的 INSERT 和 SELECT 权限
GRANT INSERT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO anon;
GRANT INSERT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO authenticated;
GRANT SELECT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO anon;
GRANT SELECT (id, ad_type, type, content, imgs, admin_id, created_at) ON public.advertisements TO authenticated;

-- 12. 刷新 REST API 缓存（重要！）
NOTIFY pgrst, 'reload schema';

-- 完成！
-- 现在你应该能够在管理员端保存广告，并在会员端看到广告了。

